---
# vars file for capsule
admin: admin_user_name
admin_passwd: admin_password
satellite: node-3
sub: false
version: 6.7
loadbalancer: false
capsule: node-2

capsule_certs: /root/capsule_cert

repos67:
  - rhel-7-server-rpms
  - rhel-7-server-satellite-capsule-6.6-rpms
  - rhel-7-server-satellite-maintenance-6-rpms
  - rhel-7-server-satellite-tools-6.7-rpms
  - rhel-server-rhscl-7-rpms
  - rhel-7-server-ansible-2.8-rpms

repos66:
  - rhel-7-server-rpms
  - rhel-7-server-satellite-capsule-6.6-rpms
  - rhel-7-server-satellite-maintenance-6-rpms
  - rhel-7-server-satellite-tools-6.6-rpms
  - rhel-server-rhscl-7-rpms
  - rhel-7-server-ansible-2.8-rpms

packages:
  - satellite-capsule
  - chrony
  - sos

ports:
  - 53/tcp
  - 53/udp
  - 67/udp
  - 69/udp
  - 80/tcp
  - 443/tcp
  - 5000/tcp
  - 5647/tcp
  - 8000/tcp
  - 8140/tcp
  - 8443/tcp
  - 9090/tcp
