---
- name: Install the Tower RPM.
  yum:
    name: '{{tower_package_rpm}}'
    enablerepo: "{{ ansible_tower_repo }},{{ ansible_tower_dependency_repo }}"
    disable_gpg_check: '{{ not gpgcheck | bool }}'
    update_cache: yes
    state: latest
  tags: packages_el_yum_install_tower

- name: Upgrade Ansible
  yum:
    name: ansible
    state: latest
    enablerepo: "{{ ansible_tower_dependency_repo }}"
  when: upgrade_ansible_with_tower

- name: Upgrade dependencies
  yum:
    name: '*'
    exclude: 'ansible'
    enablerepo: "{{ ansible_tower_dependency_repo }}"
    disablerepo: "*"
    disable_gpg_check: '{{ not gpgcheck | bool }}'
    update_cache: yes
    state: latest
