---
- name: clean metadata
  command: yum clean all 
  args:
    warn: false

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
   
- name: run upgrade command
  command: satellite-maintain upgrade run --target-version {{ version }} -y

- name: reboot
  command: reboot
  ignore_errors: yes
