---
- name: selinux to enforcing
  lineinfile:
    regexp: "^SELINUX="
    state: present
    path: /etc/selinux/config
    line: SELINUX=enforcing

- name: enabling packages
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ repositories }}"

- name: package present
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: enable and start ntpd
  service:
    name: ntpd
    state: started
    enabled: yes

- name: Remove swapfile from /etc/fstab
  mount:
    fstype: swap
    state: absent
    name: none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: empty file
  copy:
    content: ""
    dest: /etc/sysconfig/docker-storage-setup

- name: configuring docker storage
  blockinfile: 
    block: |
      DEVS=/dev/vdb
      VG=docker_vg
      DATA_SIZE=99%VG
      STORAGE_DRIVER="overlay2"
      CONTAINER_ROOT_LV_NAME="docker-root-lv"
      CONTAINER_ROOT_LV_SIZE="100%FREE"
      CONTAINER_ROOT_LV_MOUNT_PATH="/var/lib/docker"
      EXTRA_STORAGE_OPTIONS="--storage-opt overlay2.override_kernel_check=true --storage-opt overlay2.size=40G --graph=/var/lib/docker"        
    path: /etc/sysconfig/docker-storage-setup

- name: docker-storage-setup
  shell: docker-storage-setup

- name: enable and start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: enabling repositories on localhost
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ repositories }}"
  delegate_to: localhost

- name: install openshift-ansible on localhost
  package:
    name: openshift-ansible
    state: present
  delegate_to: localhost
