---
- name: install firewalld
  package:
    name: firewalld
    state: present

- name: open firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ ports }}"

- name: reloading firewalld service
  systemd:
    name: firewalld
    state: reloaded 
#This task in not necessary in a newly used cluster   
   #- name: clean metadata
   #  command: yum clean all 

#This task in not necessary in a newly used cluster
   #- name: update
   #  yum:
   #    name: '*'
   #    state: latest

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
   
- name: enable and start chronyd
  service:
    name: chronyd
    state: started
    enabled: yes

- name: execute satellite-installer command
  command: "{{ satellite_cmd }}" 


