---
- name: Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled

- name: Enable necessary repos satellite
  rhsm_repository:
    name: "{{ item }}"
  loop: "{{ repos67 }}"
  when: version == "6.7"

- name: Enable necessary repos satellite
  rhsm_repository:
    name: "{{ item }}"
  loop: "{{ repos66 }}"
  when: version == "6.6"
