---
- name: Create a directory for job stdout
  file:
    path: '{{ backup_dir.rstrip("/") }}/{{ now }}/job_status/'
    group: root
    mode: 0700
    owner: root
    state: directory

- name: Copy Job stdout from Tower
  shell: rsync -auq /var/lib/awx/job_status/ {{ backup_dir.rstrip("/") }}/{{ now }}/job_status/
