---
- name: install firewalld
  package:
    name: firewalld
    state: present

- name: open firewall ports
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ services }}"

- name: reloading firewalld service
  systemd:
    name: firewalld
    state: reloaded 
#This task in not necessary in a newly used cluster   
   #- name: clean metadata
   #  command: yum clean all 

#This task in not necessary in a newly used cluster
   #- name: update
   #  yum:
   #    name: '*'
   #    state: latest

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
   
- name: line
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_all_ipv4_addresses | first }} {{ ansible_fqdn }} {{ ansible_hostname }}"

- name: execute satellite-installer command
  command: "{{ satellite_cmd }}" 


