---
- name: Remove the restore directory.
  file:
    path: '{{ backup_dir.rstrip("/") }}/restore/'
    state: absent

- name: start web service.
  service:
    name: nginx
    state: started

- name: start supervisord.
  service:
    name: supervisord
    state: started

