tower_firewall_type: none

tower_firewall_ports:
  - "{{ firewalld_http_port }}"
  - "{{ firewalld_https_port }}"

tower_firewall_ha_ports: []

tower_cluster_management_ports:
  - 4369
  - 25672
  - 15672

database_firewall_ports:
  - "{{ pg_port }}"

tower_firewalld_zone: public
