---
- name: Disable all RHSM repositories
  rhsm_repository:
    name: "*"
    state: disabled
  when: capsule == ansible_hostname

- name: Enable necessary repos capsule 6.7
  rhsm_repository:
    name: "{{ item }}"
  loop: "{{ repos67 }}"
  when: 
    - version == 6.7
    - capsule == ansible_hostname

- name: Enable neccesary repos capsule 6.6
  rhsm_repository:
    name: "{{ item }}"
  loop: "{{ repos66 }}"
  when: 
    - version == 6.6
    - capsule == ansible_hostname
