---
- name: Disable all RHSM repositories
  rhsm_repository:
    name: "*"
    state: disabled

- name: Enable necessary repos capsule
  rhsm_repository:
    name: "{{ item }}"
  loop: "{{ repos67 }}"
