- name: set basic capsule cmd installation
  set_fact:
    capsule_basic_cmd: "/usr/sbin/satellite-installer --scenario capsule"

- name: Get settings list of the satellite
  command: "hammer --username='{{ admin }}' --password='{{ admin_passwd }}' --output='json' settings list"
  register: satellite_settings_output
  delegate_to: "{{ satellite }}"
  run_once: true

- name: Set facts for the satellite settings output
  set_fact:
    satellite_settings: "{{ satellite_settings_output.stdout | from_json }}"

- name: Get consumer key and consumer secret from satellite settings output
  set_fact:
    satellite_oauth_consumer_key: "{{ satellite_settings | json_query(oauth_consumer_key_query) | first }}"
    satellite_oauth_consumer_secret: "{{ satellite_settings | json_query(oauth_consumer_secret_query) | first }}"
  vars:
    oauth_consumer_key_query: "[?Name=='oauth_consumer_key'].Value"
    oauth_consumer_secret_query: "[?Name=='oauth_consumer_secret'].Value"

- name: set capsule install vars
  set_fact:
    capsule_deployment_answers:
      "foreman-proxy-foreman-base-url": "https://{{ satellite }}"
      "foreman-proxy-trusted-hosts": "{{ ansible_fqdn }}"
      "foreman-proxy-content-parent-fqdn": "{{ satellite }}"
      "foreman-proxy-register-in-foreman": 'true'
      "foreman-proxy-oauth-consumer-key": "{{ satellite_oauth_consumer_key }}"
      "foreman-proxy-oauth-consumer-secret": "{{ satellite_oauth_consumer_secret }}"
      "puppet-server-foreman-url": "https://{{ ansible_fqdn }}"
      "certs-tar-file": "{{ capsule_certs_file }}"
    when: not loadbalancer

- name: Get final command of satellite installer
  set_fact:
    capsule_cmd: "{{ capsule_basic_cmd }} --{{ item.key }}='{{ item.value }}'"
  loop: "{{ capsule_deployment_answers | dict2items }}"

