---
- name: install firewalld
  package:
    name: firewalld
    state: present
  delegate_to: "{{ capsule }}"

- name: open firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ ports }}"
  delegate_to: "{{ capsule }}"

- name: reloading firewalld service
  systemd:
    name: firewalld
    state: reloaded
  delegate_to: "{{ capsule }}"

#This task in not necessary in a newly used cluster   
   #- name: clean metadata
   #  command: yum clean all 

#This task in not necessary in a newly used cluster
   #- name: update
   #  yum:
   #    name: '*'
   #    state: latest

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
  delegate_to: "{{ capsule }}"
   
- name: enable and start chronyd
  service:
    name: chronyd
    state: started
    enabled: yes
  delegate_to: "{{ capsule }}"
     
- name: create directory for storing certificates
  file:
    path: /root/capsule_cert
    state: directory
  delegate_to: "{{ satellite }}"

- name: copy script to satellite
  copy:
    src: generate_certs.sh
    dest: generate_certs.sh
    mode: 0755
  delegate_to: "{{ satellite }}"
        
- name: execute script for generating certificates of the capsule
  script: generate_certs.sh
  delegate_to: "{{ satellite }}"

- name: bring certs to localhost
  copy:
    src:
    dest:
  

- name: copy certs to capsule
  copy:
    src:
    dest:

- name: run capsule installer cmd
  command: "{{ capsule_cmd }}"

#    - name: download satellite ca-consumer
#      get_url:
#        url: https://node-1.edutest.lab.upshift.rdu2.redhat.com/pub/katello-ca-consumer-latest.noarch.rpm
#        dest: .
#        validate_certs: false

#    - name: install katello-ca-consumer
#      yum:
#        name: katello-ca-consumer-latest.noarch.rpm
#        state: present

