---
- name: Ensure that tower job_status directory exists.
  file:
    group: "awx"
    mode: 0755
    owner: "awx"
    path: "/var/lib/awx/job_status"
    state: directory

- name: Restore job stdout
  shell: rsync -aq {{ backup_dir.rstrip("/") }}/restore/job_status/ /var/lib/awx/job_status/
  when: has_host_archive
